const galleryData = [
    {
        id: "galleryIbadan",
        title: "Gallery Ibadan Training",
        images: [
            "/images/Gallery Ibadan Training/IMG_7713.jpg",
            "/images/Gallery Ibadan Training/IMG_7715.jpg",
            "/images/Gallery Ibadan Training/IMG_7738.jpg",
            "/images/Gallery Ibadan Training/IMG_7739.jpg",
            "/images/Gallery Ibadan Training/IMG_7741.jpg",
            "/images/Gallery Ibadan Training/IMG_7742.jpg",
            "/images/Gallery Ibadan Training/IMG_7743.jpg",
            "/images/Gallery Ibadan Training/IMG_7750.jpg",
            "/images/Gallery Ibadan Training/IMG_7751.jpg",
            "/images/Gallery Ibadan Training/IMG_7753.jpg",
            "/images/Gallery Ibadan Training/IMG_7759.jpg",
        ],
        description:
            "Private EdTech integration training session for teachers from Golden Beryl International School Ibadan.",
        category: "events",
    },
    {
        id: "galleryKaduna",
        title: "Gallery Kaduna Training",
        images: [
            "/images/Gallery Kaduna Training/IMG_5706.jpg",
            "/images/Gallery Kaduna Training/IMG_5756.jpg",
            "/images/Gallery Kaduna Training/IMG_5791.jpg",
            "/images/Gallery Kaduna Training/IMG_5798.jpg",
            "/images/Gallery Kaduna Training/IMG_5799.jpg",
            "/images/Gallery Kaduna Training/IMG_5838.jpg",
            "/images/Gallery Kaduna Training/IMG_5839.jpg",
            "/images/Gallery Kaduna Training/IMG_5852.JPG",
            "/images/Gallery Kaduna Training/IMG_6071.jpg",
            "/images/Gallery Kaduna Training/IMG_6094.jpg",
            "/images/Gallery Kaduna Training/IMG_6147.jpg",
        ],
        description:
            "General EdTech integration training session for teachers from a group of 5 schools in Kaduna.",
        category: "events",
    },
    {
        id: "mastercardFoundation",
        title: "Mastercard Foundation Edtech Conference",
        images: [
            "/images/Mastercard Foundation Edtech Conference/IMG_6296.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6333.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6334.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6338.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6342.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6357.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6439.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6449.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6469.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6470.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
        ],
        description: "The Mastercard Foundation Edtech conference Event.",
        category: "events",
    },
    {
        id: "seminar",
        title: "A Seminar Event",
        images: [
            "/images/workshopPhotos/IMG_7521.jpg",
            "/images/workshopPhotos/IMG_7526.jpg",
            "/images/workshopPhotos/IMG_7528.jpg",
            "/images/workshopPhotos/IMG_7530.jpg",
            "/images/workshopPhotos/IMG_7531.jpg",
            "/images/workshopPhotos/IMG_7532.jpg",
            "/images/workshopPhotos/IMG_8138.jpg",
        ],
        description: "A Seminar event with TEAZY Tech as one of the partners.",
        category: "workshops",
    },
];
export default galleryData;
